In [27]:
import  numpy as np
import  scipy as sp

In [32]:
#矩阵LU分解
from scipy.linalg import lu


def Doolittle(A:np.ndarray):
    """
    Performs LU Decomposition of a square matrix A using the Doolittle method.
    The function returns L and U, where A = L*U, L is a lower triangular matrix
    with unit diagonal elements, and U is an upper triangular matrix.
    """
    n = A.shape[0]
    L = np.eye(n,n)
    U = np.zeros_like(A)
    U[:,0]=A[:,0] #U的第一行等于A的第一行
    L[0,:]=A[0,:]/U[0,0] #L的第一列等于A的第一列除以U的第一行
    for i in range(1,n):
        for j in range(i, n):
            U[i, j] = A[i, j] - L[i, :i] @ U[:i, j]
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - L[j,:i]@U[:i,i]) / U[i, i]
    return L, U

A = np.array([[2, 1, 1], [4, 3, 3], [8, 7, 9]])
L, U = Doolittle(A)
b = np.array([1, 2, 3])
# print(f"mine:{np.linalg.inv(L)@np.linalg.inv(U)@b}")
# print(f"numpy:{np.linalg.solve(A, b)}")
print(f"mine\n{L}\n{U}")
p,l,u=lu(A)
print(f"scipy\n{l}\n{u}")

mine
[[1.         0.5        0.5       ]
 [0.         1.         0.        ]
 [0.         2.33333333 1.        ]]
[[2 0 0]
 [4 3 3]
 [8 0 2]]
scipy
[[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.5        0.66666667 1.        ]]
[[ 8.          7.          9.        ]
 [ 0.         -0.75       -1.25      ]
 [ 0.          0.         -0.66666667]]
