In [2]:
import  numpy as np
import  scipy as sp

In [15]:
#矩阵LU分解
from scipy.linalg import lu
def Doolittle(A:np.ndarray):
    """
    Performs LU Decomposition of a square matrix A using the Doolittle method.
    The function returns L and U, where A = L*U, L is a lower triangular matrix
    with unit diagonal elements, and U is an upper triangular matrix.
    """
    n = A.shape[0]
    L = np.eye(n,n)
    U = np.zeros_like(A)
    for i in range(0,n):
        U[i,:]=A[i,:]-L[i,:i]@U[:i,:] # U的第i行等于A的第i行减去L的前i行与U前i行的线性变换
        L[:,i]=(A[:,i]-L[:, :i]@U[:i,i])/U[i,i] # L的第i列等于A的第i列减去L的前i列与U第i列的线性变换
    return L, U
def Crout(A:np.ndarray):
    """
    Performs LU Decomposition of a square matrix A using the Crout method.
    The function returns L and U, where A = L*U, L is a lower triangular matrix
    with unit diagonal elements, and U is an upper triangular matrix.
    """
    n = A.shape[0]
    L = np.zeros_like(A)
    U = np.eye(n,n)
    for i in range(0,n):
        L[i:,i]=A[i:,i]-L[i:,:i]@U[:i,i] # L的第i列等于A的第i列减去L的前i列与U第i列的线性变换
        U[i,i+1:]=(A[i,i+1:]-L[i,:i]@U[:i,i+1:])/L[i,i] # U的第i行等于A的第i行减去L的前i行与U前i行的线性变换

    return L, U

A = np.array([[2, 1, 1], [4, 3, 3], [8, 7, 9]])
L0,U0=Doolittle(A)
L1,U1=Crout(A)
b = np.array([1, 2, 3])
# print(f"mine:{np.linalg.inv(L)@np.linalg.inv(U)@b}")
# print(f"numpy:{np.linalg.solve(A, b)}")
print(f"Doolittle\n{L0}\n{U0}")
print(f"Crout\n{L1}\n{U1}")

Doolittle
[[1. 0. 0.]
 [2. 1. 0.]
 [4. 3. 1.]]
[[2 1 1]
 [0 1 1]
 [0 0 2]]
Crout
[[2 0 0]
 [4 1 0]
 [8 3 2]]
[[1.  0.5 0.5]
 [0.  1.  1. ]
 [0.  0.  1. ]]
